core/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from core.forms import LoginForm
from core.views import (
    HomeView,
    IncomeCreateView,
    IncomeUpdateView,
    IncomeDeleteView,
    IncomeListView
)


urlpatterns = [
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='login.html', form_class=LoginForm
        ),
        name='login'
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(),
        name='logout'
    ),
    path('', HomeView.as_view(), name='home'),

    # income urls
    path(
        'incomes/create/',
        IncomeCreateView.as_view(),
        name='income_create'
    ),
    path(
        'incomes/<int:pk>/update/',
        IncomeUpdateView.as_view(),
        name='income_update'
    ),
    path(
        'incomes/<int:pk>/delete/',
        IncomeDeleteView.as_view(),
        name='income_delete'
    ),
    path(
        'incomes/all/',
        IncomeListView.as_view(),
        name='incomes_all'
    ),

    # app urls
    path(
        'expenses/', include('expenses.urls')
    ),
    path(
        'spaces/', include('spaces.urls')
    ),

    # admin and translation
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

spaces/urls.py
from django.urls import path
from django.contrib import admin

from spaces.views import (
    SpaceCreateView,
    SpaceUpdateView,
    SpaceListView,
    SpaceDeleteView
)


admin.autodiscover()

app_name = 'spaces'

urlpatterns = [
    path(
        'create/',
        SpaceCreateView.as_view(),
        name='space_create'
    ),
    path(
        '<int:pk>/update/',
        SpaceUpdateView.as_view(),
        name='space_update'
    ),
    path(
        '<int:pk>/delete/',
        SpaceDeleteView.as_view(),
        name='space_delete'
    ),
    path(
        'all/',
        SpaceListView.as_view(),
        name='spaces_all'
    ),
]

spaces/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Space(models.Model):
    name = models.CharField(max_length=255)
    current_amount = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        default=0
    )
    monthly_replenishment = models.DecimalField(
        max_digits=8,
        decimal_places=2
    )
    closed = models.BooleanField(default=False)
    max_amount = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = _('Space')
        verbose_name_plural = _('Spaces')
        ordering = ('name', )

    def __str__(self):
        return f"{self.name}"

    @property
    def get_absolute_url(self):
        return f"/{self.name}/"

spaces/forms.py
from django.forms import (
    ModelForm,
    TextInput,
    CheckboxInput,
)
from django.utils.translation import gettext_lazy as _

from spaces.models import Space


class SpacesForm(ModelForm):
    class Meta:
        model = Space
        fields = [
            'name',
            'monthly_replenishment',
            'closed',
            'max_amount'
        ]
        widgets = {
            'name': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': _('Name')
                }
            ),
            'monthly_replenishment': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': _('Monthly payment')
                }
            ),
            'max_amount': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': _('Max space amount')
                }
            ),
            'closed': CheckboxInput(attrs={'class': 'checkbox'})
        }

        labels = {
            'closed': _('Closed'),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        message = _('Missed required field')
        for field in self.fields:
            self.fields[field].error_messages['required'] = message

spaces/views.py
# -*- coding: utf-8 -*-

from django.urls import reverse
from django.views.generic import UpdateView, CreateView, ListView, DeleteView

from core.views import CustomLoginRequiredMixin
from spaces.forms import SpacesForm
from spaces.models import Space


class SpaceListView(CustomLoginRequiredMixin, ListView):
    model = Space
    template_name = 'spaces/spaces.html'
    context_object_name = 'spaces'


class SpaceCreateView(CustomLoginRequiredMixin, CreateView):
    model = Space
    template_name = 'spaces/space_create.html'
    form_class = SpacesForm

    def get_success_url(self):
        return reverse('spaces:spaces_all')


class SpaceUpdateView(CustomLoginRequiredMixin, UpdateView):
    model = Space
    template_name = 'spaces/space_update.html'
    form_class = SpacesForm

    def get_success_url(self):
        return reverse('spaces:spaces_all')


class SpaceDeleteView(CustomLoginRequiredMixin, DeleteView):
    model = Space
    context_object_name = 'object'

    def get_success_url(self):
        return reverse('spaces:spaces_all')

templates/spaces/space_confirm_delete.html
{% extends 'layout/base.html' %}
{% load static %}

{% block content %}

    {% include 'partials/confirm_delete.html' %}

{% endblock %}

templates/spaces/space_create.html
{% extends 'layout/base.html' %}
{% load static %}
{% load i18n %}


{% block content %}
    <div class="container">
        <div class="row mg-top">
            <div class="col-md-4 col-md-offset-4">
                {% block header %}<h4 class="text-center">{% translate "Create a space" %}</h4>{% endblock header %}
                {% include 'spaces/space_form.html' %}
            </div>
        </div>
    </div>

{% endblock content %}

templates/spaces/space_form.html
{% load static %}
{% load i18n %}

<form action="" method="post">
    {% csrf_token %}

    {% for field in form %}
        {% if field.name == 'closed' %}
            <div class="{% if field.errors %}has-error{% endif %}">
                <div class="checkbox">
                    <label for="{{ field.name }}">
                        {{ field }} {{ field.label }}
                        {{ field.errors }}
                    </label>
                </div>
            </div>
        {% else %}
            <div class="form-group {% if field.errors %}has-error{% endif %}">
                {{ field }}
                {{ field.errors }}
            </div>
        {% endif %}
    {% endfor %}

    {{ form.non_field_errors }}

    <div class="col-md-4 col-md-offset-4 text-center">
        <button type="submit" class="btn btn-primary">{% translate "Save" %}</button>
    </div>
</form>

templates/spaces/space_update.html
{% extends 'layout/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    <div class="container">
        <div class="row mg-top">
            <div class="col-md-4 col-md-offset-4">
                {% block header %}<h4 class="text-center">{% translate "Update the space" %}}</h4>{% endblock header %}
                {% include 'spaces/space_form.html' %}
            </div>
        </div>
    </div>

{% endblock content %}

templates/spaces/spaces.html
{% extends 'layout/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    <div class="container">
        {% include 'partials/aggregated_data.html' %}

        <div class="row my-4 px-3">
            <div class="col-md-6 offset-md-3">
                <div class="col-md-8 offset-md-4">
                    <a class="btn btn-primary" href="{% url 'spaces:space_create' %}">{% translate "Create a spaces" %}</a>
                </div>
            </div>
        </div>

        {% if message %}
            <h4> {{ message }} </h4>
        {% endif %}

        <div class="row my-4 px-3 justify-content-center">
            <div class="col-md-6 col-md-offset-3">
                <h4 class="text-center">{% translate "Monthly amount of spaces" %}</h4>
                <table class="table">
                    <thead>
                        <th>{% translate "Space name" %}</th>
                        <th class="text-left">{% translate "Monthly amount of space" %}</th>
                        <th>{% translate "Space closed" %}</th>
                    </thead>
                    {% for space in spaces %}
                        <tr>
                            <td class="col-md-6">
                                <a href="{% url 'spaces:space_update' space.id %}">
                                    {{ space.name }}
                                </a></td>
                            <td class="col-md-3">{{ space.monthly_replenishment }}</td>
                            <td>{{ space.closed|yesno }}</td>
                            <td>
                                <a href="{% url 'spaces:space_delete' space.id %}">
                                    {% translate "Delete" %}
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}