core/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from core.forms import LoginForm
from core.views import (
    HomeView,
    IncomeCreateView,
    IncomeUpdateView,
    IncomeDeleteView,
    IncomeListView
)


urlpatterns = [
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='login.html', form_class=LoginForm
        ),
        name='login'
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(),
        name='logout'
    ),
    path('', HomeView.as_view(), name='home'),

    # income urls
    path(
        'incomes/create/',
        IncomeCreateView.as_view(),
        name='income_create'
    ),
    path(
        'incomes/<int:pk>/update/',
        IncomeUpdateView.as_view(),
        name='income_update'
    ),
    path(
        'incomes/<int:pk>/delete/',
        IncomeDeleteView.as_view(),
        name='income_delete'
    ),
    path(
        'incomes/all/',
        IncomeListView.as_view(),
        name='incomes_all'
    ),

    # app urls
    path(
        'expenses/', include('expenses.urls')
    ),
    path(
        'spaces/', include('spaces.urls')
    ),

    # admin and translation
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

expenses/urls.py
from django.urls import path
from django.contrib import admin

from expenses import views

admin.autodiscover()

app_name = 'expenses'

urlpatterns = [
    path(
        'create/', views.ExpenseCreateView.as_view(),
        name='expense_create'
    ),
    path(
        '<int:pk>/update/',
        views.ExpenseUpdateView.as_view(),
        name='expense_update'
    ),
    path(
        '<int:pk>/delete/',
        views.ExpenseDeleteView.as_view(),
        name='expense_delete'
    ),
    path(
        'all/', views.ExpenseListView.as_view(),
        name='expenses_all'
    )
]

expenses/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Expense(models.Model):
    EXPENSE_FREQUENCY = [
        ('m', 'monthly'),
        ('d', 'daily'),
        ('w', 'weekly'),
        ('q', 'quarterly'),
        ('ba', 'bi-annual'),
        ('y', 'yearly')
    ]

    name = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    frequency = models.CharField(
        choices=EXPENSE_FREQUENCY,
        default='m',
        max_length=2
    )

    class Meta:
        verbose_name = _('Expense')
        verbose_name_plural = _('Expenses')
        ordering = ['name']

    def __str__(self):
        return f"{self.name}"

expenses/forms.py
from django.forms import ModelForm, TextInput, Select
from django.utils.translation import gettext_lazy as _

from expenses.models import Expense


class ExpensesForm(ModelForm):
    class Meta:
        model = Expense
        fields = ['name', 'amount', 'frequency']
        widgets = {
            'name': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': _('Name')
                }
            ),
            'amount': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': _('Amount')
                }
            ),
            'frequency': Select(
                attrs={
                    'class': 'form-control',
                    'placeholder': _('Frequency')
                }
            )
        }

expenses/views.py
# -*- coding: utf-8 -*-


from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse

from core.views import CustomLoginRequiredMixin
from expenses.forms import ExpensesForm
from expenses.models import Expense


class ExpenseCreateView(CustomLoginRequiredMixin, CreateView):
    model = Expense
    form_class = ExpensesForm
    template_name = 'expenses/income_create.html'

    def get_success_url(self):
        return reverse('expenses:expenses_all')


class ExpenseUpdateView(CustomLoginRequiredMixin, UpdateView):
    model = Expense
    template_name = 'expenses/income_update.html'
    form_class = ExpensesForm

    def get_success_url(self):
        return reverse('expenses:expenses_all')


class ExpenseDeleteView(CustomLoginRequiredMixin, DeleteView):
    model = Expense
    context_object_name = 'object'

    def get_success_url(self):
        return reverse('spaces:spaces_all')


class ExpenseListView(CustomLoginRequiredMixin, ListView):
    template_name = 'expenses/expenses.html'
    model = Expense
    context_object_name = 'expenses'

templates/expenses/expense_confirm_delete.html
{% extends 'layout/base.html' %}
{% load static %}

{% block content %}

    {% include 'partials/confirm_delete.html' %}

{% endblock %}

templates/expenses/expense_create.html
{% extends 'layout/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    <div class="container">
        <div class="row mg-top">
            <div class="col-md-4 col-md-offset-4">
                {% block header %}<h4 class="text-center">{% translate "Create an expense" %}</h4>{% endblock header %}

                {% include 'expenses/expense_form.html' %}

            </div>
        </div>
    </div>
{%  endblock %}

templates/expenses/expense_form.html
{% load static %}
{% load i18n %}

<form action="{% url 'expenses:expense_create' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group {% if field.errors %}has-error{% endif %}">
                {{ field }}
                {{ field.errors }}
            </div>
        {% endfor %}

        {{ form.non_field_errors }}

        <div class="col-md-4 col-md-offset-4 text-center">
            <button type="submit" class="btn btn-primary">{% translate "Save" %}</button>
        </div>
</form>

templates/expenses/expense_update.html
{% extends 'layout/base.html' %}
{% load static %}
{% load i18n %}


{% block content %}
    <div class="container">
        <div class="row mg-top">
            <div class="col-md-4 col-md-offset-4">
                {% block header %}<h4 class="text-center">{% translate "Update the expense" %}</h4>{% endblock header %}
                <form action="" method="post">
                {% csrf_token %}
                    {% include 'expenses/expense_form.html' %}
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

templates/expenses/expenses.html
{% extends 'layout/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    <div class="container">
        {% include 'partials/aggregated_data.html' %}

        <div class="row my-4 px-3">
            <div class="col-md-6 offset-md-3">
                <div class="col-md-8 offset-md-4">
                    <a class="btn btn-primary" href="{% url 'expenses:expense_create' %}">{% translate "Create an expense" %}</a>
                </div>
            </div>
        </div>

        {% if message %}
            <h4> {{ message }} </h4>
        {% endif %}

        <div class="row my-4 px-3 justify-content-center" id="all_expenses">
            <div class="col-md-6 col-md-offset-3">
                <h4 class="text-center">{% translate "All expenses" %}</h4>
                <table class="table">
                    <thead>
                        <th>{% translate "Expense" %}</th>
                        <th>{% translate "Amount" %}</th>
                    </thead>
                    {% for expense in expenses %}
                        <tr>
                            <td>
                                <a href="{% url 'expenses:expense_update' expense.id %}">
                                    {{ expense.name }}
                                </a>
                            </td>
                            <td>{{ expense.amount }}</td>
                            <td>
                                <a href="{% url 'expenses:expense_delete' expense.id %}">
                                    {% translate "Delete" %}
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}