core/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from core.forms import LoginForm
from core.views import (
    HomeView,
    IncomeCreateView,
    IncomeUpdateView,
    IncomeDeleteView,
    IncomeListView
)


urlpatterns = [
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='login.html', form_class=LoginForm
        ),
        name='login'
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(),
        name='logout'
    ),
    path('', HomeView.as_view(), name='home'),

    # income urls
    path(
        'incomes/create/',
        IncomeCreateView.as_view(),
        name='income_create'
    ),
    path(
        'incomes/<int:pk>/update/',
        IncomeUpdateView.as_view(),
        name='income_update'
    ),
    path(
        'incomes/<int:pk>/delete/',
        IncomeDeleteView.as_view(),
        name='income_delete'
    ),
    path(
        'incomes/all/',
        IncomeListView.as_view(),
        name='incomes_all'
    ),

    # app urls
    path(
        'expenses/', include('expenses.urls')
    ),
    path(
        'spaces/', include('spaces.urls')
    ),

    # admin and translation
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

expenses/urls.py
from django.urls import path
from django.contrib import admin

from expenses import views

admin.autodiscover()

app_name = 'expenses'

urlpatterns = [
    path(
        'create/', views.ExpenseCreateView.as_view(),
        name='expense_create'
    ),
    path(
        '<int:pk>/update/',
        views.ExpenseUpdateView.as_view(),
        name='expense_update'
    ),
    path(
        '<int:pk>/delete/',
        views.ExpenseDeleteView.as_view(),
        name='expense_delete'
    ),
    path(
        'all/', views.ExpenseListView.as_view(),
        name='expenses_all'
    )
]

spaces/urls.py
from django.urls import path
from django.contrib import admin

from spaces.views import (
    SpaceCreateView,
    SpaceUpdateView,
    SpaceListView,
    SpaceDeleteView
)


admin.autodiscover()

app_name = 'spaces'

urlpatterns = [
    path(
        'create/',
        SpaceCreateView.as_view(),
        name='space_create'
    ),
    path(
        '<int:pk>/update/',
        SpaceUpdateView.as_view(),
        name='space_update'
    ),
    path(
        '<int:pk>/delete/',
        SpaceDeleteView.as_view(),
        name='space_delete'
    ),
    path(
        'all/',
        SpaceListView.as_view(),
        name='spaces_all'
    ),
]

templates/layout/base.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}

{% load static %}

<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/app.css' %}"/>
    <link rel="shortcut icon" type="image" href="{% static 'images/favicon.png' %}"/>
    <title>{% block title %}Финансовый кнут Вартабаевых-Исабанянов{% endblock %}</title>
</head>
<body>
    <header class="my-4">
        <div class="row">

                <ul class="nav justify-content-center" id="nav-colour">
                  <li class="nav-item">
                    {% url 'home' as home %}
                    <a class="nav-link {% ifequal request.path home %}active{% endifequal %}" href="{{ home }}">
                        <span class="text-uppercase">{% translate "Home" %}</span>
                    </a>
                  </li>
                  <li class="nav-item">
                    {% url 'spaces:spaces_all' as spaces_all %}
                    <a class="nav-link {% ifequal request.path spaces_all %}active{% endifequal %}" href="{{ spaces_all }}">
                        <span class="text-uppercase">{% translate "Spaces" %}</span>
                    </a>
                  </li>
                  <li class="nav-item">
                    {% url 'expenses:expenses_all' as expenses_all %}
                    <a class="nav-link {% ifequal request.path regular_expenses %}active{% endifequal %}" href="{{ expenses_all }}">
                        <span class="text-uppercase">{% translate "Expenses" %}</span>
                    </a>
                  </li>
                <li class="nav-item">
                    {% url 'incomes_all' as incomes_all %}
                    <a class="nav-link {% ifequal request.path regular_expenses %}active{% endifequal %}" href="{{ incomes_all }}">
                        <span class="text-uppercase">{% translate "Incomes" %}</span>
                    </a>
                  </li>
                </ul>
        </div>
    </header>
    <div class="container">
        {% block content %}{% endblock content%}
    </div>




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>
</html>